### ISSUE TITLE
Refactor createServerlessIndex

### ISSUE THREAD

**Issue by aulorbe** [pinecone-io/pinecone-java-client#102]
Should have left this comment for previous PR, sorry but For line#72:
1. if we are checking for null of line#69, then line#72 is redundant check, we don't need it.

Similarly, if line#54 is checking for null then line#57's null check is not needed

_Originally posted by @rohanshah18 in https://github.com/pinecone-io/pinecone-java-client/pull/98#discussion_r1557768921_

**Comment by rohanshah18** [comment]
Will create a ticket to first check if the comment is still valid and implement it.
