### ISSUE TITLE
Consider moving back to builder pattern or add Kotlin shim?

### ISSUE THREAD

**Issue by rasharab** [pinecone-io/pinecone-java-client#120]
### Is this your first time submitting a feature request?

- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing functionality

### Describe the feature

As of 1.0.0, it is easy to get this wrong, seeing as types like id/namespace are the same, and since this library is written in Java, I can't use named arguments in Kotlin land.

        return index.query(
            topK ?: DEFAULT_TOP_K,
            denseVector,
            filteredSparseVector?.indicesWithUnsigned32IntList,
            filteredSparseVector?.valuesList,
            null,
            namespace,
            filter?.let { PineconeStructUtils.fromMap(it) },
            includeMetadata,
            includeValues,
        )
        
In the old way, the declarative approach towards specifying arguments was less error prone:

        val queryRequest = QueryRequest.newBuilder()
            .addAllVector(denseVector)
            .setTopK(topK ?: DEFAULT_TOP_K)
            .setIncludeMetadata(includeMetadata)
            .setIncludeValues(includeValues)
            .setNamespace(namespace)
            .apply {
                filter?.let { setFilter(PineconeStructUtils.fromMap(it)) }
                sparseVector
                    ?.takeIf { it.indicesCount in 1..MAX_SPARSE_SIZE }
                    ?.let {
                        setSparseVector(it)
                    }
            }
            .build()
            
Two questions:
1. Any reason for the transition away from a builder pattern?
2. Are you planning on releasing a Kotlin shim?

### Who will this benefit?

Anyone who find it currently a bit tedious having to deal with 5+ parameters for a function call.

### Are you interested in contributing this feature?

Sure, I can look into helping with this.

**Comment by rohanshah18** [comment]
Hi @rasharab, thanks for reporting this issue. To answer your questions in order:
1. Yes, we needed to add custom logic around the proto generated java classes which provided classes with builder pattern, so we have designed this wrapper.
2. As of now, we don't have any plans on designing Kotlin shim. If this changes anytime in future, I'll update this thread.

**Comment by rohanshah18** [comment]
Totally!! But building a builder pattern around a builder pattern is not something we are planning in near term.
