### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by rasharab** [pinecone-io/pinecone-java-client#122]
Noticed you guys have added support for the list endpoint recently.

When is the next expected release planned?

Thanks.

-Rashin

**Comment by rohanshah18** [comment]
I'll release by end of today

**Comment by rohanshah18** [comment]
[Java SDK v1.1.0](https://github.com/pinecone-io/pinecone-java-client/releases/tag/v1.1.0) is released and it includes list endpoint.
