### ISSUE TITLE
totalVectorCount_ is an int but would overflow >2B

### ISSUE THREAD

**Issue by krugster** [pinecone-io/pinecone-java-client#147]
Given that we expect multi-billion vector counts, I think this (and potentially other areas throughout the code?) need to be updated to int64.

https://github.com/pinecone-io/pinecone-java-client/blob/e5f79bb81e1d1748f4f6ff13c66d10442440c309/src/main/java/io/pinecone/proto/DescribeIndexStatsResponse.java#L192

**Comment by rohanshah18** [comment]
Closing this issue since we have an internal ticket for @krugster to track.
