### ISSUE TITLE
[Bug] NoSuchMethodError`MetadataUtils.attachHeaders` during PineconeConnection init

### ISSUE THREAD

**Issue by serodriguez68** [pinecone-io/pinecone-java-client#22]
### Is this a new bug?

- [X] I believe this is a new bug
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

I updated my `io.grpc.stub` dependency from 1.57.2 to 1.58.0 and in the process the code interacting with the pinecone client broke because it is no longer able to instantiate a connection the same way it used to do.  The code in question is:

```kotlin
val realPineconeClient = PineconeClient(clientConfig) # succeeds
val realPineconeConnection = realPineconeClient.connect(config.indexName) # fails with NoSuchMethodError
```
I believe the problem is caused by this line of code inside `.<init>(PineconeConnection.java:48)`
![image](https://github.com/pinecone-io/pinecone-java-client/assets/11022424/35d932c2-17e8-423a-8604-adae1460eda0)

The core of the issue seems to be that `attachHeaders` does not exist in io.grpc.stub v 1.58.0 and you have a  dependency on [1.53.0](https://github.com/pinecone-io/pinecone-java-client/blob/main/build.gradle#L22C7-L22C7)

### Expected Behavior

It should work with no error.

### Steps To Reproduce

1. With `io.grpc.stub v 1.58.0` pinned
2. Create a pineconeConnection using a valid config
3. You should see the come up

### Relevant log output

```shell
Relevant part of the stack trace


'io.grpc.stub.AbstractStub io.grpc.stub.MetadataUtils.attachHeaders(io.grpc.stub.AbstractStub, io.grpc.Metadata)'
java.lang.NoSuchMethodError: 'io.grpc.stub.AbstractStub io.grpc.stub.MetadataUtils.attachHeaders(io.grpc.stub.AbstractStub, io.grpc.Metadata)'
	at io.pinecone.PineconeConnection.<init>(PineconeConnection.java:48)
	at io.pinecone.PineconeClient.connect(PineconeClient.java:37)
	at io.pinecone.PineconeClient.connect(PineconeClient.java:27)
```
```


### Environment
```markdown
- **OS**: MacOS 13.5.2 
- **Language version**: kotlin("jvm") version "1.9.10"
- **Pinecone client version**: 0.2.3, through to 0.4.0
```

**Comment by rohanshah18** [comment]
@serodriguez68 I've updated the gRPC version to `v1.58.0`, the latest released java-sdk [v0.5.1](https://github.com/pinecone-io/pinecone-java-client/releases/tag/v0.5.1) should've the updates.

**Comment by rohanshah18** [comment]
Closing this issue since I haven't heard back, assuming this is working fine for you.

**Comment by serodriguez68** [comment]
Sorry for the late reply. I updated the client to v0.6.0 and I can confirm that this particular problem went away.  I'll file a different issue if I encounter any other problems.

Thanks for looking into this.
