### ISSUE TITLE
[Feature] Using a higher sourceCompatibility version

### ISSUE THREAD

**Issue by russcam** [pinecone-io/pinecone-java-client#39]
### Is this your first time submitting a feature request?

- [X] I have searched the existing issues, and I could not find an existing issue for this feature
- [X] I am requesting a straightforward extension of existing functionality

### Describe the feature

The current sourceCompatibility is `JavaVersion.VERSION_1_8`

https://github.com/pinecone-io/pinecone-java-client/blob/eef17f845a60a7902fd1187aae8f8e54791d08ee/build.gradle#L15

This source compatibility restricts language features to Java 8 and doesn't allow newer language features like `var`, switch expressions, etc.

Is there any impediment to allowing source to use newer language features?

### Describe alternatives you've considered

Remain using Java 8 language features

### Who will this benefit?

All contributors to this project!

**Comment by rohanshah18** [comment]
@russcam The only requirement is it must be compatible with java 8+ versions and some of the consumers of this sdk strictly rely on java 8.

**Comment by rohanshah18** [comment]
Closing this issue now since it's non blocking and as mentioned in the description, we can still keep using java 8 features.
