### ISSUE TITLE
When will listIndexes be supported ?

### ISSUE THREAD

**Issue by JackMatthewRimmer** [pinecone-io/pinecone-java-client#49]
Hello !
Will the `listIndexes` be apart of the next release, if so when is that going to be released ?

**Comment by rohanshah18** [comment]
Yes, `listIndexes` is part of the next release and its planned for the week of 12/18.

**Comment by JackMatthewRimmer** [comment]
Ok thank you !

**Comment by rohanshah18** [comment]
@JackMatthewRimmer I have released the new version `0.7.1` which has support for `listIndexes()` and `configureIndex()`.
Release page: https://github.com/pinecone-io/pinecone-java-client/releases/tag/v0.7.1

**Comment by JackMatthewRimmer** [comment]
Thank you 🙏
