### ISSUE TITLE
[Bug] getUserAgent throwing exception "Unable to extract pinecone client version"

### ISSUE THREAD

**Issue by JackMatthewRimmer** [pinecone-io/pinecone-java-client#54]
### Is this a new bug?

- [X] I believe this is a new bug
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

When I call listIndexes with some valid credentials an exception is thrown with "Unable to extract pinecone client version".
its is looking for a gradle.properties file in a multi modules project. Where the module it is being used does not have a gradle.properties file and throwing an error.

### Expected Behavior

It would be able to resolve the user agent string or allow for manually setting the version to stop it throwing an exception

### Steps To Reproduce

Create a multi module gradle project where one of the sub modules does not have a gradle.properties file and try and send a request to pinecone. and exception will be thrown.

### Environment

```markdown
- **Ubuntu**:
- **17n**:
- **0.7.1**:
```

**Comment by ToluwaniO** [comment]
Experiencing this with `0.7.1` as well

**Comment by rasharab** [comment]
Experiencing this as well.

**Comment by rohanshah18** [comment]
@JackMatthewRimmer @ToluwaniO @rasharab what is the environment of the index created in pinecone console? `gcp-starter` by any chance?

**Comment by shalk** [comment]
I meet the same problem,I found  pinecone-java 0.7.1 was reading  the file `gradle.properties`
Maybe the project use pincone-java-client is  a maven project  and  the file was not exist.

I think the client version can be keep in  source code like https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/internal/GrpcUtil.java#L223 or some version file keept in jar

**Comment by JackMatthewRimmer** [comment]
@rohanshah18 Yes it was

**Comment by rohanshah18** [comment]
@JackMatthewRimmer thanks for confirming. For `gcp-starter` environment, I'll be releasing the changes in 3 weeks for all index related operations but in the meantime, please feel free to use the pinecone console. As far as vector operations, they are expected to work.

**Comment by marcoalkema** [comment]
@rohanshah18 This would apply to Maven as well? I'm currently experiencing this error with Maven.

**Comment by rohanshah18** [comment]
@marcoalkema No, we haven't rolled out the support yet. Please use the console. Thanks!

**Comment by escuelatech** [comment]
Is this issue got resolved ? if so, what is the fix

**Comment by rohanshah18** [comment]
I have released [Java SDK v0.7.2](https://github.com/pinecone-io/pinecone-java-client/releases/tag/v0.7.2) which should fix the above issue. Thanks everyone for your patience and please let me know if you continue to see this issue.

**Comment by rohanshah18** [comment]
I released Java SDK `v0.7.2` which should fix the `Unable to extract pinecone client version` error.

**Comment by JackMatthewRimmer** [comment]
@rohanshah18 I am now getting a 404 exception with the correct api key and environment I notice in the docs for list indexes its uses the url 

https://controller.us-east1-gcp.pinecone.io/databases

however in the PineconeIndexOperationClient i have noticed

public static final String BASE_URL_SUFFIX = ".pinecone.io/databases/";

contains an extra slash. Is this correct ?

**Comment by JackMatthewRimmer** [comment]
Im closing this issue as this is resolved and raising a new one for the above as I have checked it in postman and get a 404 with the slash

**Comment by rohanshah18** [comment]
@JackMatthewRimmer thanks for raising the issue. You're correct and that's the support I'll be rolling out by the end of this week. Note that this issue is only for the `gcp-starter` environments and is being tracked by this issue already:
https://github.com/pinecone-io/pinecone-java-client/issues/46

In the meantime, to unblock you, you can use `describeIndex` call to get the `host`, which can be further used to instantiate `PineconeConnection` object and finally the `blocking` or the `future` stub, as shown below:
```java
PineconeClientConfig config = new PineconeClientConfig()
        .withApiKey(System.getenv("PINECONE_API_KEY"))
        .withEnvironment(System.getenv("PINECONE_ENVIRONMENT"));
PineconeIndexOperationClient controlPlaneClient = new PineconeIndexOperationClient(config);
String indexName = "index-name";
PineconeClient dataPlaneClient = new PineconeClient(config);
IndexMeta indexMeta = controlPlaneClient.describeIndex(indexName);
String host = indexMeta.getStatus().getHost();

 PineconeConnection connection = dataPlaneClient.connect(
        new PineconeConnectionConfig()
                .withConnectionUrl("https://" + host));
VectorServiceGrpc.VectorServiceBlockingStub blockingStub = connection.getBlockingStub();

String namespace = RandomStringBuilder.build("ns", 8);

// upsert
float[][] upsertData = {{1.0F, 2.0F, 3.0F}, {4.0F, 5.0F, 6.0F}, {7.0F, 8.0F, 9.0F}};
List<String> upsertIds = Arrays.asList("v1", "v2", "v3");
List<Vector> upsertVectors = new ArrayList<>();

for (int i = 0; i < upsertData.length; i++) {
    upsertVectors.add(Vector.newBuilder()
            .addAllValues(Floats.asList(upsertData[i]))
            .setMetadata(Struct.newBuilder()
                    .putFields("some_field", Value.newBuilder().setNumberValue(i).build())
                    .build())
            .setId(upsertIds.get(i))
            .build());
}

UpsertRequest request = UpsertRequest.newBuilder()
        .addAllVectors(upsertVectors)
        .setNamespace(namespace)
        .build();

UpsertResponse upsertResponse = blockingStub.upsert(request);
logger.info("Put " + upsertResponse.getUpsertedCount() + " vectors into the index");
assert (upsertResponse.getUpsertedCount() == 3);
```

**Comment by JackMatthewRimmer** [comment]
@rohanshah18 I am trying to list indexes given ApiKey and Environment name so I am unable to use describeIndex(indexName) in this manner for my use case

**Comment by rohanshah18** [comment]
@JackMatthewRimmer yes, you wont be able to list indexes yet. Just provided some context for data plane operations. I'll try to release the updated SDK version by the end of this week. Thanks!

**Comment by JackMatthewRimmer** [comment]
@rohanshah18 Legend, Thank you ! take care

**Comment by rohanshah18** [comment]
@JackMatthewRimmer I had a few unexpected things to take care of this week. But create and list indexes are the first things I'll handle starting next week. Sorry for the delay. Hope you have a great weekend.

**Comment by JackMatthewRimmer** [comment]
@rohanshah18 You too and no worries, thanks for the update 😄
