### ISSUE TITLE
[Bug] Please bring back vector_service.proto file

### ISSUE THREAD

**Issue by nsadeh** [pinecone-io/pinecone-java-client#71]
### Is this a new bug?

- [X] I believe this is a new bug
- [X] I have searched the existing issues, and I could not find an existing issue for this bug

### Current Behavior

Commit 26a134847ae825b41ae178bf81d8576db5be526c removes the vector_service.proto file and replaces them with generated java classes. The rationale is as follows:

```
## Problem

    The SDK uses vector_service.proto file which is out of sync with the
    actual version.

    ## Solution

    Replace vector_service.proto with java generated classes
```

The vector_service.proto files are incredibly important documentation. They are needed by users to understand how to use the clients. The generated Java classes are not designed for human readers and are impossible to read and understand, making the client nearly unusable.

Just a suggestion - if the vector_service.proto file is out of date, why not bring it up to date instead of removing it?

### Expected Behavior

vector_service.proto should be available as important documentation.

### Steps To Reproduce

N/A

### Environment

```markdown
N/A
```

**Comment by nsadeh** [comment]
For example: I came to this repo today to understand if I can perform a query search and a metadata filter in the same query, and that's really hard to see without the proto file.

**Comment by rohanshah18** [comment]
Yes, we are planning to publish the updated vector_service.proto file. Will update you once we have finalized it.

**Comment by nsadeh** [comment]
Hi, any movement here? I am re-writing portion of my Pinecone code and it's hard to do the object mapping without the proto file

**Comment by nsadeh** [comment]
Hello, it's been nearly 3 months - any updates here?

**Comment by rohanshah18** [comment]
@nsadeh As of now, the plan is to not publish the proto file as a part of Java SDK but it is on our roadmap to share the proto file but we don't have specific timelines yet. I'll like to better understand your needs on why you need the proto file and from what I understand, you need it for:
1. Better object mapping
2. To understand if you can perform a query search and a metadata filter in the same query

Would you please elaborate on 1? As far as 2 is concerned, we do have the overloaded methods available in the Index or AsyncIndex classes for each data plan operation, so I hope that's helpful in the meantime.

**Comment by rohanshah18** [comment]
Since I haven't heard back from you @nsadeh for sometime now, so I'll close this issue but please feel free to re-open if you need additional assistance.
